simplesocial/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "accounts"

urlpatterns = [
	path('login/',auth_views.LoginView.as_view(template_name='accounts/login.html'), name="login"),
	path('logout/',auth_views.LogoutView.as_view(), name="logout"),
	path('signup/',views.SignUp.as_view(),name='signup'),
]

simplesocial/posts/urls.py
from django.urls import path 
from . import views 

app_name = 'posts'

urlpatterns = [ 
	path('',views.PostList.as_view(),name='all'),
	path('new/',views.CreatePost.as_view(),name='create'),
	path('by/<username>/',views.UserPosts.as_view(),name='for_user'),
	path('by/<username>/<pk>/',views.PostDetail.as_view(),name='single'),
	path('deleted/<pk>/',views.DeletePost.as_view(),name='delete'),	
	]

simplesocial/simplesocial/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from . import views
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(),name='home'),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('test/',views.TestPage.as_view(),name='test'),
    path('thanks',views.ThanksPage.as_view(),name='thanks'),
    path("posts/", include("posts.urls", namespace="posts")),
    path("groups/",include("groups.urls", namespace="groups")),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/',include(debug_toolbar.urls))
    ] + urlpatterns

simplesocial/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<meta charset="utf-8">
	<title>Star Social</title>

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>

        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>

		<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>

		<link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">

		<link rel="stylesheet" href="{% static 'css/master.css'%}">
		
</head>
<body>
	{{flag}}


	<nav class="navbar mynav" role="navigation" id='navbar'>
		<div class="container">
			<a class="navbar-brand mynav" href="{% url 'home' %}">Star Social</a>

			<ul class="nav navbar-nav">
				{% if user.is_authenticated %}
					<li><a href="{% url 'posts:create' %}">Post</a></li>
					<li><a href="{% url 'groups:all' %}">Groups</a></li>
					<li><a href="{% url 'groups:create' %}">Create Group</a></li>
					<li><a href="{% url 'accounts:logout' %}">Log out</a></li>
					

				{% else %}
					<li><a href="{% url 'groups:all' %}">Groups</a></li>
					<li><a href="{% url 'accounts:login' %}">Login</a></li>
					<li><a href="{% url 'accounts:signup' %}">Sign Up</a></li>

				{% endif %}
			</ul>

        

	<div class="container mycontent">
    

		{% block content %}


		{% endblock %}
		
	</div>



	
</body>
<script src="{% static "simplesocial/js/master.js"%}" type="text/javascript" ></script>
</html>

simplesocial/templates/grouped_list.html
<h1>HI</h1>
<div class="groupslist">
<div class="col-md-8">
	<div class="card card-with-shadow">
		<div class="content">
			<h3 class="mygroup-title">Your Groups</h3>
			<ol class="list-unstyled">
				{% for member_group in get_user_groups %}
				<li class="group li-with-bullet">
					<a href="{% url 'groups:single' slug=member_group.slug %}">{{ member_group.name }}</a></li>
				<hr>
				{% endfor %}
			</ol>
		    <h3 class="allgroup-title">All Groups</h3>
			<ul class="list-unstyled">
				{% for other_group in get_other_groups %}
				<li class="group li-with-bullet">
					<a href="{% url 'groups:single'  slug=other_group.slug %}">{{other_group.name}}</a></li>
				<hr>
				{% endfor %}
		    </ul>
		</div>
	</div>
</div>
</div>

simplesocial/templates/index.html
{% extends 'base.html' %}

{% block content %}
<div class="main-title">
	<h1>Welcome to Star Social!</h1>
</div>
{% endblock %}

simplesocial/templates/test.html
{% extends 'base.html' %}
{% block content %}
<div class="logged">
	<h1>You are now logged in</h1>
</div>
{% endblock %}

simplesocial/templates/thanks.html
{% extends 'base.html' %}
{% block content %}
<div class="logged-out">
	<h1>Thanks for visiting. Come back soon!</h1>
</div>
{% endblock %}