simplesocial/posts/urls.py
from django.urls import path 
from . import views 

app_name = 'posts'

urlpatterns = [ 
	path('',views.PostList.as_view(),name='all'),
	path('new/',views.CreatePost.as_view(),name='create'),
	path('by/<username>/',views.UserPosts.as_view(),name='for_user'),
	path('by/<username>/<pk>/',views.PostDetail.as_view(),name='single'),
	path('deleted/<pk>/',views.DeletePost.as_view(),name='delete'),	
	]

simplesocial/simplesocial/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from . import views
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(),name='home'),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('test/',views.TestPage.as_view(),name='test'),
    path('thanks',views.ThanksPage.as_view(),name='thanks'),
    path("posts/", include("posts.urls", namespace="posts")),
    path("groups/",include("groups.urls", namespace="groups")),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/',include(debug_toolbar.urls))
    ] + urlpatterns

simplesocial/posts/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from django.contrib import messages
from django.shortcuts import redirect
from groups.models import Group,GroupMember
from django.contrib.auth import get_user_model
User = get_user_model()

class Post(models.Model):
	user = models.ForeignKey(User,related_name='posts',null=True,on_delete=models.CASCADE)
	created_at = models.DateTimeField(auto_now=True)
	message = models.TextField()
	group = models.ForeignKey(Group,related_name='posts',null=True,on_delete=models.CASCADE)

	def __str__(self):
		return self.message

	def get_absolute_url(self):
			return reverse('posts:single',kwargs={'username':self.user.username,'pk':self.pk})

	class Meta:
		ordering = ['-created_at']



# Create your models here.

simplesocial/posts/forms.py
from django import forms
from .models import Post
from groups.models import Group,GroupMember

class PostForm(forms.ModelForm):
	class Meta:
		model = Post
		fields = ['message','group']
	def __init__(self,user,*args,**kwargs):																																									
		super(PostForm,self).__init__(*args,**kwargs)
		members = GroupMember.objects.prefetch_related('user').filter(user__username__contains=user)
		members = members.select_related('group')
		group_list = []
		for member in members:
			group_list.append(member.group.name)
		self.fields['group'].queryset = Group.objects.filter(name__in=group_list)

simplesocial/posts/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.http import Http404
from django.views import generic
from braces.views import SelectRelatedMixin
from django.contrib.messages.views import SuccessMessageMixin
from . import models
from . import forms
from django.contrib import messages
from django.contrib.auth import get_user_model
from groups.models import GroupMember,Group
from .forms import PostForm
User = get_user_model()

class PostList(SelectRelatedMixin,generic.ListView):
	model = models.Post
	select_related = ('user',)
	template_name = 'post_list'

class UserPosts(SelectRelatedMixin,generic.ListView):
	model = models.Post
	select_related = ('user',)
	template_name = 'posts/user_post_list.html'

	def get_queryset(self):
		try:
			self.post_user = User.objects.get(username__iexact=self.request.user)

		except User.DoesNotExist:
			raise Http404
		else:
			return self.post_user.posts.all()

	def get_context_data(self,**kwargs):
		context = super().get_context_data(**kwargs)
		context['post_user'] = self.post_user
		return context

class PostDetail(SelectRelatedMixin,generic.DetailView):
	model = models.Post
	select_related = ('user','group')

	def get_queryset(self):
		queryset = super().get_queryset()
		return queryset.filter(user__username__iexact=self.kwargs.get('username'))

class CreatePost(LoginRequiredMixin,SelectRelatedMixin,generic.CreateView):

	model = models.Post
	form_class = PostForm

	def get_form_kwargs(self):
		kwargs = super(CreatePost,self).get_form_kwargs()
		kwargs['user'] = self.request.user
		return kwargs

	def form_valid(self,form):
		self.object = form.save(commit = False)
		self.object.user = self.request.user 
		self.object.save()
		return super().form_valid(form)

class DeletePost(LoginRequiredMixin,SelectRelatedMixin,generic.DeleteView):
	model = models.Post 
	select_related = ('user','group')
	success_url = reverse_lazy('posts:all')

	def get_queryset(self):
		queryset = super().get_queryset()
		return queryset.filter(user_id = self.request.user.id)


	def delete(self,*args,**kwargs):
		messages.success(self.request,'deleted')
		return super().delete(*args,**kwargs)

simplesocial/posts/templates/posts/_post.html
<div class="post-media">
	<h3 id="post-message">{{post.message|safe}}</h3>
	<div class="media-body">
		<h5 class="media-heading">
		<span class="username">
			<a href="{% url 'posts:for_user' username=post.user.username %}">@{{post.user.username}}
		</span>
		<time class="time">
			<a href="{% url 'posts:single' username=post.user.username pk=post.pk %}">
			{{post.created_at}}</a>
		</time>
		</h5>
 {% if not flag %}	
		<div class="media-footer">
			{% if user.is_authenticated and post.user == user %}
			<a href="{% url 'posts:delete' pk=post.pk %}" title="delete" class="btn btn-danger btn-large btn-default">
				<span class="glyphicon glyphicon-remove"></span> Delete</a>
			{% endif %}
			<hr>

		</div>
 {% endif %}		
	</div>
</div>

simplesocial/posts/templates/posts/post_base.html
{% extends 'base.html' %}

{% block content %}
<div class="posts-page">
	<div class="container">
		<div class="row">
			{% block prepost %}{% endblock %}
			{% block post_content %}{% endblock %}
			{% block post_post %}{% endblock %}
		</div>
	</div>
</div>

{% endblock %}

simplesocial/posts/templates/posts/post_confirm_delete.html
{% extends 'posts/post_base.html' %}

{% block post_content %}
<style type="text/css">

</style>
<div class="deletion">
	<h3>Are you sure you want to delete this post?</h3>
</div>



<div class="posts">
	{% include 'posts/_post.html' with  flag=True  %}
</div>

<form method="POST">
<div class="confirm-delete">
	{% csrf_token %}
	<input type="submit" value="Confirm Delete" class="btn btn-danger btn-large">
	<a href="{% url 'posts:single' username=user.username pk=object.pk %}" class="btn btn-simple btn-large btn-default">Cancel</a>
</div>
</form>

{% endblock post_content %}

simplesocial/posts/templates/posts/post_detail.html
{% extends 'posts/post_base.html' %}

{% block post_content %}
<div class="col-md-8">
	{% include 'posts/_post.html' %}
</div>
{%  endblock %}

simplesocial/posts/templates/posts/post_form.html
{% extends 'posts/post_base.html' %}
{% load bootstrap4 %}

{% block post_content %}
<h4 id="new-post">Create a new post</h4>
<div class="create-post">
	<form action="{% url 'posts:create' %}" method="post" id='postForm'>
		{% csrf_token %}
		{% bootstrap_form form %}
		<input type="submit" class="btn btn-primary btn-large" value="Post">
	</form>	
</div>
{% endblock %}

simplesocial/posts/templates/posts/post_list.html
{% extends 'posts/post_base.html' %}

{% block post_content %}
<div class="col-md-8">
	{% for post in post_list %}
		{% include 'posts/_post.html' %}
	{% endfor %}

</div>

{% endblock %}

simplesocial/posts/templates/posts/user_post_list.html
{% extends 'posts/post_base.html' %}

{% block prepost %}
	<div class="col-md-4">
		<h1 id="post-username">@{{post_user.username}}</h1>
	</div>
{% endblock %}

{% block post_content %}
<div class="col-md-8">
	{% for post in post_list %}
	{% include 'posts/_post.html' %}
	{% endfor %}
</div>

{% endblock %}