simplesocial/groups/urls.py
from django.urls import path 
from . import views


app_name = 'groups'
urlpatterns = [
	path('',views.ListGroups.as_view(),name='all'),
	path('new/',views.CreateGroup.as_view(),name='create'),
	path('posts/in/<slug>/',views.SingleGroup.as_view(),name='single'),
	path('join/<slug>/',views.JoinGroup.as_view(),name='join'),
	path('leave/<slug>/',views.LeaveGroup.as_view(),name='leave'),
	path('delete/<int:pk>/',views.DeleteGroup,name='delete'),
]

simplesocial/posts/urls.py
from django.urls import path 
from . import views 

app_name = 'posts'

urlpatterns = [ 
	path('',views.PostList.as_view(),name='all'),
	path('new/',views.CreatePost.as_view(),name='create'),
	path('by/<username>/',views.UserPosts.as_view(),name='for_user'),
	path('by/<username>/<pk>/',views.PostDetail.as_view(),name='single'),
	path('deleted/<pk>/',views.DeletePost.as_view(),name='delete'),	
	]

simplesocial/simplesocial/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from . import views
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(),name='home'),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('test/',views.TestPage.as_view(),name='test'),
    path('thanks',views.ThanksPage.as_view(),name='thanks'),
    path("posts/", include("posts.urls", namespace="posts")),
    path("groups/",include("groups.urls", namespace="groups")),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/',include(debug_toolbar.urls))
    ] + urlpatterns

simplesocial/groups/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse
from django.contrib import admin

from django.contrib.auth import get_user_model
User = get_user_model()

from django.contrib import admin

from django import template
register = template.Library()
# Create your models here.

class Group(models.Model):
	name = models.CharField(max_length=255,unique=True)
	admin = models.ForeignKey(User,null=True,on_delete=models.CASCADE,related_name='owned_group')
	slug = models.SlugField(allow_unicode=True,unique=True) 
	description = models.TextField(blank=True,default='')
	description_html = models.TextField(editable=False,default='',blank=True)
	members = models.ManyToManyField(User,through="GroupMember")

	def __str__(self):
		return self.name

	def save(self,*args,**kwargs):
		self.slug = slugify(self.name)
		self.description_html = self.description
		super().save(*args,**kwargs)

	def get_absolute_url(self):
		return reverse('groups:single',kwargs={'slug':self.slug})


'''class ArticleAdmin():
		def save_model(self, request, obj, form, change):
			print(request.user)
			print(obj.name)
			super().save_model(request, obj, form, change)'''

class GroupMember(models.Model):
	group = models.ForeignKey(Group,related_name='memberships',on_delete=models.CASCADE)
	user = models.ForeignKey(User,related_name='user_groups',on_delete=models.CASCADE)

	def __str__(self):
		return self.user.username

	class Meta:
		unique_together = ('group','user')

simplesocial/groups/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin,PermissionRequiredMixin
from django.urls import reverse
from django.views import generic
from django.shortcuts import get_object_or_404
from django.contrib import messages
from groups.models import Group,GroupMember
from django.db import IntegrityError
from . import models
from braces.views import PrefetchRelatedMixin
from django.contrib.auth import get_user_model
from django.http import HttpResponseRedirect
from django.urls import reverse
User = get_user_model()
# Create your views here.

class CreateGroup(LoginRequiredMixin,generic.CreateView):
	fields = ('name','description')
	model = Group

	def form_valid(self,form):
		user = User.objects.get(username=self.request.user)
		form.instance.admin = user
		form.save()
		return super(CreateGroup, self).form_valid(form)

class SingleGroup(PrefetchRelatedMixin,generic.DetailView):
	model = Group
	prefetch_related = ['posts','members']

class ListGroups(PrefetchRelatedMixin,generic.ListView):
	model = Group
	prefetch_related = ['posts','members']

class JoinGroup(LoginRequiredMixin,generic.RedirectView):

	def get_redirect_url(self,*args,**kwargs):
		return reverse('groups:single',kwargs={'slug':self.kwargs.get('slug')})

	def get(self,request,*args,**kwargs):
		group = get_object_or_404(Group,slug=self.kwargs.get('slug'))

		try:
			GroupMember.objects.create(user=self.request.user,group=group)
		except IntegrityError:
			messages.warning(self.request,"Warning. Already a member")
		else:
			messages.success(self.request,'You are now a member')

		return super().get(request,*args,**kwargs)

class LeaveGroup(LoginRequiredMixin,generic.RedirectView):

	def get_redirect_url(self,*args,**kwargs):
		return reverse('groups:single',kwargs={'slug':self.kwargs.get('slug')})

	def get(self,request,*args,**kwargs):

		try:
			membership = models.GroupMember.objects.filter(
					user=self.request.user,
					group__slug=self.kwargs.get('slug')
				).get()

		except models.GroupMember.DoesNotExist:
			messages.warning(self.request,'Sorry. You are not in this group')

		else:
			membership.delete()
			messages.success(self.request,"You have successfully left this group")

		return super().get(request, *args, **kwargs)

def DeleteGroup(request,pk):
	if  request.method == 'GET':
		group = get_object_or_404(Group,pk=pk)
		if group.admin == request.user:
			group.delete()
	return HttpResponseRedirect(reverse('groups:all'))

simplesocial/groups/templates/groups/group_base.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
	<div class="row">
		{% block pregroup %}{% endblock %}
		{% block group_content %}{% endblock %}
		{% block postgroup %}{% endblock %}
	</div>
</div>
{% endblock %}

simplesocial/groups/templates/groups/group_detail.html
{% extends 'groups/group_base.html' %}
{% block pregroup %}

<h1 id="group-name">{{group.name}}</h1>
<div class="content">
	

</div>
<h2 id="mem-count">Member Count: {{group.members.count}}</h2>
{% if user in group.members.all %}

		<a href="{% url 'groups:leave' slug=group.slug %}" class='leave-or-join btn btn-lg btn-fill btn-warning'>
			<span class="glyphicon glyphicon-remove-circle"> Leave</span></a>

	{% else %}

		<a href="{% url 'groups:join' slug=group.slug %}" class='leave-or-join btn btn-lg btn-fill btn-warning'>
			<span class="glyphicon glyphicon-ok-circle"> Join</span></a>

{% endif %}

{%if group.admin == request.user %}
	
	<a href="{% url 'groups:delete' pk=group.pk %}" class='delete btn btn-lg btn-fill btn-warning'>
			<span class="glyphicon glyphicon-remove-circle"> Delete Group</span></a>

{% endif %}


{% endblock %}


{% block group_content %}
<div class="col-md-8">
<div class="group-posts">
	{% if group.posts.count == 0 %}
		<h2 id="no-post">No Posts in the group yet</h2>
	{% else %}
		{% for post in group.posts.all %}
			{% include "posts/_post.html" %}
		{% endfor %}
	{% endif %}
</div>


</div>

{% endblock %}

simplesocial/groups/templates/groups/group_form.html
{% extends 'groups/group_base.html' %}
{% load bootstrap4 %}

{% block group_content %}
<h4 id="new-group">New group</h4>

	<form action="{% url 'groups:create' %}" method="post" id='groupForm'>
		{% csrf_token %}
		{% bootstrap_form form %}
		<input type="submit" class="btn btn-primary btn-large" value="Create">
	</form>	
{% endblock %}

simplesocial/groups/templates/groups/group_list.html
{% extends 'groups/group_base.html' %}

{% block pregroup %}
	<div class="col-md-4">
		<div class="content">
			{% if user.is_authenticated %}
				<h2 id="group-header">Welcome back
					<a href="{% url 'posts:for_user' username=user.username %}">@{{user.username}}</a></h2>
			{% endif %}
	<div class="group-label">
			<h2>Groups</h2>
			<p>Welcome to the Groups page</p>
	</div>

	</div>

		{% if user.is_authenticated %}
		<a id="create-group" href="{% url 'groups:create' %}" class="btn btn-md btn-fill btn-warning">
		<span class="glyphicon glyphicon-plus-sign"> New Group</span>
		</a>
		{% endif %}
	</div>
	{% endblock %}

{% block group_content %}
<div class="col-md-8">
	<div class="list-group">
		{% for group in object_list %}
		<a class="list-group-item" href="{% url 'groups:single' slug=group.slug %}">
			<h3 class="title list-group-item-heading">{{group.name}}</h3>
			<div class="list-group-item-text container-fluid">
				{{group.description_html|safe}}
				<div class="row">
					<div class="col-md-4">
						<span class="badge">{{group.members.count}}</span>
						member{{group.members.count|pluralize}}
					</div>
					<div class="col-md-4">
						<span class="badge">{{group.posts.count}}</span>
						post{{group.posts.count|pluralize}}
					</div>

				</div>


			</div>
		</a>
		{% endfor %}
	</div>
</div>	
{% endblock %}	
			

simplesocial/groups/templates/groups/my_groups_list.html
{% extends 'base.html' %}
<div class="col-md-4">
	{% if request.user.is_authenticated %}
	<div class="card card-with-shadow">
		<div class="content">
			<h5 class="title">Your Groups</h5>
			<ul class="list-unstyled">
				{% for member_group in get_user_groups %}
				<li class="group li-with-bullet">
					<a href="{% url 'groups:single' slug=member_group.group.slug %}">{{ member_group.group.name }}</a></li>
				{% endfor %}
			</ul>
		</div>
	</div>
	{% endif %}
	<div class="card card-with-shadow">
		<div class="content">
			<h3 class="title">All Groups</h3>
			<ul class="list-unstyled">
				{% for other_group in get_other_groups %}
				<li class="group li-with-bullet">
					<a href="{% url 'groups:single'  slug=other_group.slug %}">{{other_group.name}}</a></li>
				{% endfor %}
				

			</ul>
				
		</div>
	</div>
</div>